apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ramakant6520/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'client/src/**/*'
            dest: "/app/src"
    # - image: ramakant6520/comments
    #   context: comments
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '*.js'
    #         dest: .
    # - image: ramakant6520/event-bus
    #   context: event-bus
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '*.js'
    #         dest: .
    # - image: ramakant6520/moderation
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '*.js'
    #         dest: .
    # - image: ramakant6520/posts
    #   context: posts
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '*.js'
    #         dest: .
    # - image: ramakant6520/query
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '*.js'
    #         dest: .